version: '3.8'

services:
  app:
    build: .
    container_name: golangApp
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      DB_PATH: /app/data/golangApp.db
