version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: golangApp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: R00t!Pa$$w0rd#2024
      MYSQL_DATABASE: golangApp
      MYSQL_USER: golangApp_user
      MYSQL_PASSWORD: G0l@ngApp#P@ss2024
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: golangApp
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: golangApp_user
      DB_PASSWORD: G0l@ngApp#P@ss2024
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: golangApp

volumes:
  db_data:
